create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  title text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.notes enable row level security;
revoke all on table public.notes from anon, authenticated;
revoke all on sequence public.notes_id_seq from anon, authenticated;

comment on table public.notes is
  '2단계 학습용 가상 메모. 실제 개인정보나 비밀값을 저장하지 않습니다.';
